### PR TITLE
45 private

### LINKED ISSUE #45: Private Style Guides
Let's add support for private style guide search

### PR DESCRIPTION
**Pull request by tenji240**
Closes #45 and #47 
Adding Support for Private Guides
See the UX Flow here: http://recordit.co/aPTyIIqnh0

### CODE REVIEW

**Comment by tenji240** [comment]
Support for Private Style Guides are completed. Screenshots Below
screen shot 2015-07-13 at 5 03 03 pm
screen shot 2015-07-13 at 5 03 15 pm

**Comment by RedPenPal** [comment]
Google Docs plugin is looking great and I’m so glad we’re all banging on it!

Couple aesthetic tweaks for Settings tab:

- If user has not previously selected a style guide, default selection should be Editor’s Picks, if that’s not already the case

- Let’s put public search and private search in their own dedicated search section, underneath the admin-favorited public style guides, which would be displayed as follows:

Search public style guides:
[text entry field]

Access a private style guide:
[text entry field]

- Per another thread, I’m hoping that the user accesses a private style guide by entering just the code, not the entire URL.

**Comment by RedPenPal** [comment]
Sorry, just now seeing your latest email.  It’s OK if user needs to paste the entire private guide URL (rather than just the code) into the Google Docs plugin, so long as we don’t think that’s too unorthordox of a UX.  That means the dedicated search section should display as follows (adding text into the text entry field, in yellow highlight):

Search public style guides:
[text entry field with “name of guide” as grey text that disappears when you cursor into the field]

Access a private style guide:
[text entry field with “URL of your private guide” as grey text that disappears when you cursor into the field]

From: Charles Best <charles@donorschoose.org<mailto:charles@donorschoose.org>>
Date: Thursday, July 16, 2015 at 9:43 AM
To: MustWin/irregardless-docs-addon <reply@reply.github.com<mailto:reply@reply.github.com>>, MustWin/irregardless-docs-addon <irregardless-docs-addon@noreply.github.com<mailto:irregardless-docs-addon@noreply.github.com>>
Cc: Tenji Tembo <tenji@mustwin.com<mailto:tenji@mustwin.com>>, Frankie Cheung <cheungf@gmail.com<mailto:cheungf@gmail.com>>
Subject: Re: [irregardless-docs-addon] 45 private (#46)

Google Docs plugin is looking great and I’m so glad we’re all banging on it!

Couple aesthetic tweaks for Settings tab:

- If user has not previously selected a style guide, default selection should be Editor’s Picks, if that’s not already the case

- Let’s put public search and private search in their own dedicated search section, underneath the admin-favorited public style guides, which would be displayed as follows:

Search public style guides:
[text entry field]

Access a private style guide:
[text entry field]

- Per another thread, I’m hoping that the user accesses a private style guide by entering just the code, not the entire URL.

**Comment by tenji240** [comment]
Yeah no worries. On the main site, it's setup so that all the user has to do is click on the private style guide URL and it get's copied to their clipboard (for now it works on Chrome, but we're working to extend it to all browsers) and then they can just paste it into the access input box.

**Pull request merged**
